# Generated by Django 5.0.2 on 2026-03-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Номер дела / Суд')),
                ('start_date', models.DateField(verbose_name='Дата регистрации дела')),
                ('status', models.CharField(choices=[('active', 'В производстве'), ('finished', 'Завершено')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Судебное дело',
                'verbose_name_plural': 'Судебные дела',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО / Название клиента')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ответчика')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Ответчик',
                'verbose_name_plural': 'Ответчики',
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('decision', 'Судебное решение (первая инстанция)'), ('appeal', 'Подача апелляции'), ('execution', 'Получение исп. листа')], max_length=50, verbose_name='Этап')),
                ('date_planned', models.DateField(verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус: Выполнено')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.case')),
            ],
            options={
                'verbose_name': 'Событие дела',
                'verbose_name_plural': 'События дел',
                'ordering': ['date_planned'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.defendant', verbose_name='Ответчик'),
        ),
    ]
