# Generated by Django 5.0.2 on 2026-03-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_as_defendant', to='main.client', verbose_name='Ответчик'),
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('plaintiff', 'Истец (Клиент)'), ('defendant', 'Ответчик'), ('third_party', '3-я сторона')], default='plaintiff', max_length=20, verbose_name='Процессуальный статус'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_as_plaintiff', to='main.client', verbose_name='Истец (Клиент)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО / Название'),
        ),
        migrations.DeleteModel(
            name='Defendant',
        ),
    ]
