# Generated by Django 5.0.2 on 2026-03-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_case_defendant_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('decision', 'Судебное решение'), ('appeal', 'Срок подачи апелляции'), ('execution', 'Исполнительное производство')], max_length=50, verbose_name='Этап'),
        ),
    ]
